#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Hiroto Yasuhara
# SPDX-License-Identifier: BSD-3-Clause

import sys

mos = sys.argv[1]
lv = sys.argv[2]
st = sys.argv[3]

print("{}が現れた。レベル:{} 属性:{}".format(mos, lv, st))
