#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Hiroto Yasuhara
# SPDX-License-Identifier: BSD-3-Clause

mos = input("名前を入力: ")
lv = input("レベルを入力: ")
st = input("属性を入力: ")

print("{}が現れた。レベル:{} 属性:{}".format(mos, lv, st))
